'use strict'

var BURGER_SMALL_PRICE = 50;
var BURGER_SMALL_CALORIE = 20;
var BURGER_BIG_PRICE = 100;
var BURGER_BIG_CALORIE = 40;
var CHEESE_PRICE = 10;
var CHEESE_CALORIE = 20;
var LETTUCE_PRICE = 20;
var LETTUCE_CALORIE = 5;
var POTATO_PRICE = 15;
var POTATO_CALORIE = 10;
var CAESAR_PRICE = 100;
var CAESAR_CALORIE = 20;
var OLIVIER_PRICE = 50;
var OLIVIER_CALORIE = 80;
var COLA_PRICE = 50;
var COLA_CALORIE = 40;
var COFFEE_PRICE = 80;
var COFFEE_CALORIE = 20;